### ISSUE TITLE
TiDB in Kubernetes has both "Configure" and "Reference/Configuration"

### ISSUE THREAD

**Issue by gregwebs** [pingcap/docs#1433]
## Change Request

It took me a while to find the local PV document because I assumed it would be under "Configure/". Others [may be having trouble](https://github.com/pingcap/tidb-operator/issues/740) also. Why do we have configuration in 2 places?

I would prefer to remove the "Reference" heading and just use Configur(e/ation). Promote "Tools" to the top-level.

**Comment by dcalvin** [comment]
@gregwebs This is arranged so that we could scale our documentation with a nice structure. Configure under How-to is task-oriented, while Configuration under Reference is reference oriented (configuration commands, items, descriptions).  We can take one out for now but in the long run, with many more configuration items added, the structure will be messy. 

Also we are re-designing our website, with some optimized navigations (TiDB in K8s to be parallel to traditional deployment, and landing pages for all major topics so that you could find everything you need at a glance.)

**Comment by ran-huang** [comment]
Closing this issue because it's outdated. We have refactored the documentation.

If you still have questions about the doc structure, feel free to reopen the issue or create a new one.
