### ISSUE TITLE
`proxy-protocol` possible values are not rendered correctly

### ISSUE THREAD

**Issue by yahonda** [pingcap/docs#16511]
File: [/master/tiproxy/tiproxy-configuration.md](https://docs.pingcap.com/tidb/dev/tiproxy-configuration)

https://docs.pingcap.com/tidb/dev/tiproxy-configuration#proxy-protocol shows the one of possible value is missing the closing backquote.

```
Possible values: `, v2`
```
The markdown itself looks correct https://github.com/pingcap/docs/blame/965c8767ee121c4bab722ee1e30a6c705481d8a5/tiproxy/tiproxy-configuration.md#L84

**Comment by kennytm** [comment]
No the markdown is not correct. Commonmark allows inline code blocks to be surrounded by N+1 backquotes in order to display N backquotes inside, e.g. 

```markdown
Quote identifiers (schema/table/column names) with the `` ` `` character like ``SELECT * FROM `x`.`y`;``.
```

Therefore using ` `` ` will not work for empty strings. (But separating it like `` ` ` `` is also incorrect as this seems to suggest that a space is a valid input to `proxy-protocol`.)

The [tidb-server page](https://docs.pingcap.com/tidb/stable/tidb-configuration-file#compression-new-in-v800) uses `""` for empty strings, but they will also use `"v2"` for consistency.
