### ISSUE TITLE
ADMIN CHECKSUM TABLE command undocumented

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#956]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

The command added here is completely undocumented https://github.com/pingcap/tidb/pull/6067

2. Describe your suggestion or addition.

I expect there would be some documentation here: https://pingcap.com/docs/sql/admin/#admin-statement

3. Provide some reference materials (documents, websites, etc) if you could.

As well as the commit referenced above, this command appears to be used by lightning.

**Comment by kennytm** [comment]
@morgo  In #663 the `admin show slow` statement was documented in `sql/slow-query.md` instead of `sql/admin.md`. Do you think it is better to document `admin checksum table` in `tools/lightning/*`?

Additionally there are several undocumented ADMIN statements like `admin check table`, `admin check index`, `admin cleanup index` etc (not related to Lightning).

**Comment by morgo** [comment]
@kennytm I think they should all be documented :-)  There is no harm in mentioning them in both places.

**Comment by morgo** [comment]
`ADMIN` is now documented here:
https://pingcap.com/docs/v3.0/reference/sql/statements/admin/

It makes sense to break this into sub-statement documentation though.

**Comment by nullnotnil** [comment]
I will close this and handle in https://github.com/pingcap/docs/issues/2639
